/**
 * KeyboardEvent: key property
 *
 * The **logical** value of the key pressed by the user, taking into
 * consideration the state of modifier keys such as Shift as well as the
 * keyboard locale and layout. I.e.: if user pressing `shift+/`, the logical
 * value will be `?`.
 *
 * @see https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key
 */
export enum Key {
  // Special values
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#special_values
  Unidentified,

  // Modifier keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#modifier_keys
  Alt,
  AltGraph,
  CapsLock,
  Control,
  Fn, // no event fired for this key
  FnLock, // no event fired for this key
  Hyper,
  Meta,
  NumLock,
  ScrollLock,
  Shift,
  Super,
  Symbol,
  SymbolLock,

  // Whitespace keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#whitespace_keys
  Enter,
  Tab,
  Space,

  // Navigation keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#navigation_keys
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  End,
  Home,
  PageDown,
  PageUp,

  // Editing keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#editing_keys
  Backspace,
  Clear,
  Copy,
  CrSel,
  Cut,
  Delete,
  EraseEof,
  ExSel,
  Insert,
  Paste,
  Redo,
  Undo,

  // UI keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#ui_keys
  Accept,
  Again,
  Attn,
  Cancel,
  ContextMenu,
  Escape,
  Execute,
  Find,
  Finish,
  Help,
  Pause,
  Play,
  Props,
  Select,
  ZoomIn,
  ZoomOut,

  // Device keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#device_keys
  BrightnessDown,
  BrightnessUp,
  Eject,
  LogOff,
  Power,
  PowerOff,
  PrintScreen,
  Hibernate,
  Standby,
  WakeUp,

  // TODO: these value aren't usable for keymapping, should remove those value
  //  and handle keypress during IME composition probably.
  // Common IME keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#common_ime_keys
  AllCandidates,
  Alphanumeric,
  CodeInput,
  Compose,
  Convert,
  Dead,
  FinalMode,
  GroupFirst,
  GroupLast,
  GroupNext,
  GroupPrevious,
  ModeChange,
  NextCandidate,
  NonConvert,
  PreviousCandidate,
  Process,
  SingleCandidate,

  // Korean keyboards only
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#korean_keyboards_only
  HangulMode,
  HanjaMode,
  JunjaMode,

  // Japanese keyboards only
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#japanese_keyboards_only
  Eisu,
  Hankaku,
  Hiragana,
  HiraganaKatakana,
  KanaMode,
  KanjiMode,
  Katakana,
  Romaji,
  Zenkaku,
  ZenkakuHanaku,

  // Phone keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#phone_keys
  AppSwitch,
  Call,
  Camera,
  CameraFocus,
  EndCall,
  GoBack,
  GoHome,
  HeadsetHook,
  LastNumberRedial,
  Notification,
  MannerMode,
  VoiceDial,

  // Multimedia keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#multimedia_keys
  ChannelDown,
  ChannelUp,
  MediaFastForward,
  MediaPause,
  MediaPlay,
  MediaPlayPause,
  MediaRecord,
  MediaRewind,
  MediaStop,
  MediaTrackNext,
  MediaTrackPrevious,

  // Audio control keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#audio_control_keys
  AudioBalanceLeft,
  AudioBalanceRight,
  AudioBassDown,
  AudioBassBoostDown,
  AudioBassBoostToggle,
  AudioBassBoostUp,
  AudioBassUp,
  AudioFaderFront,
  AudioFaderRear,
  AudioSurroundModeNext,
  AudioTrebleDown,
  AudioTrebleUp,
  AudioVolumeDown,
  AudioVolumeMute,
  AudioVolumeUp,
  MicrophoneToggle,
  MicrophoneVolumeDown,
  MicrophoneVolumeMute,
  MicrophoneVolumeUp,

  // TV control keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#tv_control_keys
  TV,
  TV3DMode,
  TVAntennaCable,
  TVAudioDescription,
  TVAudioDescriptionMixDown,
  TVAudioDescriptionMixUp,
  TVContentsMenu,
  TVDataService,
  TVInput,
  TVInputComponent1,
  TVInputComponent2,
  TVInputComposite1,
  TVInputComposite2,
  TVInputHDMI1,
  TVInputHDMI2,
  TVInputHDMI3,
  TVInputHDMI4,
  TVInputVGA1,
  TVMediaContext,
  TVNetwork,
  TVNumberEntry,
  TVPower,
  TVRadioService,
  TVSatellite,
  TVSatelliteBS,
  TVSatelliteCS,
  TVSatelliteToggle,
  TVTerrestrialAnalog,
  TVTerrestrialDigital,
  TVTimer,

  // Media controller keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#media_controller_keys
  AVRInput,
  AVRPower,
  ColorF0Red,
  ColorF1Green,
  ColorF2Yellow,
  ColorF3Blue,
  ColorF4Grey,
  ColorF5Brown,
  ClosedCaptionToggle,
  Dimmer,
  DisplaySwap,
  DVR,
  Exit,
  FavoriteClear0,
  FavoriteClear1,
  FavoriteClear2,
  FavoriteClear3,
  FavoriteRecall0,
  FavoriteRecall1,
  FavoriteRecall2,
  FavoriteRecall3,
  FavoriteStore0,
  FavoriteStore1,
  FavoriteStore2,
  FavoriteStore3,
  Guide,
  GuideNextDay,
  GuidePreviousDay,
  Info,
  InstantReplay,
  Link,
  ListProgram,
  LiveContent,
  Lock,
  MediaApps,
  MediaAudioTrack,
  MediaLast,
  MediaSkipBackward,
  MediaSkipForward,
  MediaStepBackward,
  MediaStepForward,
  MediaTopMenu,
  NavigateIn,
  NavigateNext,
  NavigateOut,
  NavigatePrevious,
  NextFavoriteChannel,
  NextUserProfile,
  OnDemand,
  Pairing,
  PinPDown,
  PinPMove,
  PinPToggle,
  PinPUp,
  PlaySpeedDown,
  PlaySpeedReset,
  PlaySpeedUp,
  RandomToggle,
  RcLowBattery,
  RecordSpeedNext,
  RfBypass,
  ScanChannelsToggle,
  ScreenModeNext,
  Settings,
  SplitScreenToggle,
  STBInput,
  STBPower,
  Subtitle,
  Teletext,
  VideoModeNext,
  Wink,
  ZoomToggle,

  // Speech recognition keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#speech_recognition_keys
  SpeechCorrectionList,
  SpeechInputToggle,

  // Document keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#document_keys
  Close,
  New,
  Open,
  Print,
  Save,
  SpellCheck,
  MailForward,
  MailReply,
  MailSend,

  // Application selector keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#application_selector_keys
  LaunchCalculator,
  LaunchCalendar,
  LaunchContacts,
  LaunchMail,
  LaunchMediaPlayer,
  LaunchMusicPlayer,
  LaunchMyComputer,
  LaunchPhone,
  LaunchScreenSaver,
  LaunchSpreadsheet,
  LaunchWebBrowser,
  LaunchWebCam,
  LaunchWordProcessor,
  LaunchApplication1,
  LaunchApplication2,
  LaunchApplication3,
  LaunchApplication4,
  LaunchApplication5,
  LaunchApplication6,
  LaunchApplication7,
  LaunchApplication8,
  LaunchApplication9,
  LaunchApplication10,
  LaunchApplication11,
  LaunchApplication12,
  LaunchApplication13,
  LaunchApplication14,
  LaunchApplication15,
  LaunchApplication16,

  // Browser control keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#browser_control_keys
  BrowserBack,
  BrowserFavorites,
  BrowserForward,
  BrowserHome,
  BrowserRefresh,
  BrowserSearch,
  BrowserStop,

  // Numeric keypad keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#numeric_keypad_keys
  Decimal,
  Key11,
  Key12,
  Multiply,
  Add,
  NumpadClear,
  Divide,
  Subtract,
  Separator,
  Key0,
  Key1,
  Key2,
  Key3,
  Key4,
  Key5,
  Key6,
  Key7,
  Key8,
  Key9,

  MAX_VALUE,
}

export const namedKeys = new Map<string, Key>([
  // Special values
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#special_values
  ['Unidentified', Key.Unidentified],

  // Modifier keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#modifier_keys
  ['Alt', Key.Alt],
  ['AltGraph', Key.AltGraph],
  ['CapsLock', Key.CapsLock],
  ['Control', Key.Control],
  ['Fn', Key.Fn],
  ['FnLock', Key.FnLock],
  ['Hyper', Key.Hyper],
  ['Meta', Key.Meta],
  ['NumLock', Key.NumLock],
  ['ScrollLock', Key.ScrollLock],
  ['Shift', Key.Shift],
  ['Super', Key.Super],
  ['Symbol', Key.Symbol],
  ['SymbolLock', Key.SymbolLock],

  // Whitespace keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#whitespace_keys
  ['Enter', Key.Enter],
  ['Tab', Key.Tab],
  ['Space', Key.Space],

  // Navigation keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#navigation_keys
  ['ArrowDown', Key.ArrowDown],
  ['ArrowLeft', Key.ArrowLeft],
  ['ArrowRight', Key.ArrowRight],
  ['ArrowUp', Key.ArrowUp],
  ['End', Key.End],
  ['Home', Key.Home],
  ['PageDown', Key.PageDown],
  ['PageUp', Key.PageUp],

  // Editing keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#editing_keys
  ['Backspace', Key.Backspace],
  ['Clear', Key.Clear],
  ['Copy', Key.Copy],
  ['CrSel', Key.CrSel],
  ['Cut', Key.Cut],
  ['Delete', Key.Delete],
  ['EraseEof', Key.EraseEof],
  ['ExSel', Key.ExSel],
  ['Insert', Key.Insert],
  ['Paste', Key.Paste],
  ['Redo', Key.Redo],
  ['Undo', Key.Undo],

  // UI keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#ui_keys
  ['Accept', Key.Accept],
  ['Again', Key.Again],
  ['Attn', Key.Attn],
  ['Cancel', Key.Cancel],
  ['ContextMenu', Key.ContextMenu],
  ['Escape', Key.Escape],
  ['Execute', Key.Execute],
  ['Find', Key.Find],
  ['Finish', Key.Finish],
  ['Help', Key.Help],
  ['Pause', Key.Pause],
  ['Play', Key.Play],
  ['Props', Key.Props],
  ['Select', Key.Select],
  ['ZoomIn', Key.ZoomIn],
  ['ZoomOut', Key.ZoomOut],

  // Device keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#device_keys
  ['BrightnessDown', Key.BrightnessDown],
  ['BrightnessUp', Key.BrightnessUp],
  ['Eject', Key.Eject],
  ['LogOff', Key.LogOff],
  ['Power', Key.Power],
  ['PowerOff', Key.PowerOff],
  ['PrintScreen', Key.PrintScreen],
  ['Hibernate', Key.Hibernate],
  ['Standby', Key.Standby],
  ['WakeUp', Key.WakeUp],

  // Common IME keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#common_ime_keys
  ['AllCandidates', Key.AllCandidates],
  ['Alphanumeric', Key.Alphanumeric],
  ['CodeInput', Key.CodeInput],
  ['Compose', Key.Compose],
  ['Convert', Key.Convert],
  ['Dead', Key.Dead],
  ['FinalMode', Key.FinalMode],
  ['GroupFirst', Key.GroupFirst],
  ['GroupLast', Key.GroupLast],
  ['GroupNext', Key.GroupNext],
  ['GroupPrevious', Key.GroupPrevious],
  ['ModeChange', Key.ModeChange],
  ['NextCandidate', Key.NextCandidate],
  ['NonConvert', Key.NonConvert],
  ['PreviousCandidate', Key.PreviousCandidate],
  ['Process', Key.Process],
  ['SingleCandidate', Key.SingleCandidate],

  // Korean keyboards only
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#korean_keyboards_only
  ['HangulMode', Key.HangulMode],
  ['HanjaMode', Key.HanjaMode],
  ['JunjaMode', Key.JunjaMode],

  // Japanese keyboards only
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#japanese_keyboards_only
  ['Eisu', Key.Eisu],
  ['Hankaku', Key.Hankaku],
  ['Hiragana', Key.Hiragana],
  ['HiraganaKatakana', Key.HiraganaKatakana],
  ['KanaMode', Key.KanaMode],
  ['KanjiMode', Key.KanjiMode],
  ['Katakana', Key.Katakana],
  ['Romaji', Key.Romaji],
  ['Zenkaku', Key.Zenkaku],
  ['ZenkakuHanaku', Key.ZenkakuHanaku],

  // Phone keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#phone_keys
  ['AppSwitch', Key.AppSwitch],
  ['Call', Key.Call],
  ['Camera', Key.Camera],
  ['CameraFocus', Key.CameraFocus],
  ['EndCall', Key.EndCall],
  ['GoBack', Key.GoBack],
  ['GoHome', Key.GoHome],
  ['HeadsetHook', Key.HeadsetHook],
  ['LastNumberRedial', Key.LastNumberRedial],
  ['Notification', Key.Notification],
  ['MannerMode', Key.MannerMode],
  ['VoiceDial', Key.VoiceDial],

  // Multimedia keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#multimedia_keys
  ['ChannelDown', Key.ChannelDown],
  ['ChannelUp', Key.ChannelUp],
  ['MediaFastForward', Key.MediaFastForward],
  ['MediaPause', Key.MediaPause],
  ['MediaPlay', Key.MediaPlay],
  ['MediaPlayPause', Key.MediaPlayPause],
  ['MediaRecord', Key.MediaRecord],
  ['MediaRewind', Key.MediaRewind],
  ['MediaStop', Key.MediaStop],
  ['MediaTrackNext', Key.MediaTrackNext],
  ['MediaTrackPrevious', Key.MediaTrackPrevious],

  // Audio control keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#audio_control_keys
  ['AudioBalanceLeft', Key.AudioBalanceLeft],
  ['AudioBalanceRight', Key.AudioBalanceRight],
  ['AudioBassDown', Key.AudioBassDown],
  ['AudioBassBoostDown', Key.AudioBassBoostDown],
  ['AudioBassBoostToggle', Key.AudioBassBoostToggle],
  ['AudioBassBoostUp', Key.AudioBassBoostUp],
  ['AudioBassUp', Key.AudioBassUp],
  ['AudioFaderFront', Key.AudioFaderFront],
  ['AudioFaderRear', Key.AudioFaderRear],
  ['AudioSurroundModeNext', Key.AudioSurroundModeNext],
  ['AudioTrebleDown', Key.AudioTrebleDown],
  ['AudioTrebleUp', Key.AudioTrebleUp],
  ['AudioVolumeDown', Key.AudioVolumeDown],
  ['AudioVolumeMute', Key.AudioVolumeMute],
  ['AudioVolumeUp', Key.AudioVolumeUp],
  ['MicrophoneToggle', Key.MicrophoneToggle],
  ['MicrophoneVolumeDown', Key.MicrophoneVolumeDown],
  ['MicrophoneVolumeMute', Key.MicrophoneVolumeMute],
  ['MicrophoneVolumeUp', Key.MicrophoneVolumeUp],

  // TV control keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#tv_control_keys
  ['TV', Key.TV],
  ['TV3DMode', Key.TV3DMode],
  ['TVAntennaCable', Key.TVAntennaCable],
  ['TVAudioDescription', Key.TVAudioDescription],
  ['TVAudioDescriptionMixDown', Key.TVAudioDescriptionMixDown],
  ['TVAudioDescriptionMixUp', Key.TVAudioDescriptionMixUp],
  ['TVContentsMenu', Key.TVContentsMenu],
  ['TVDataService', Key.TVDataService],
  ['TVInput', Key.TVInput],
  ['TVInputComponent1', Key.TVInputComponent1],
  ['TVInputComponent2', Key.TVInputComponent2],
  ['TVInputComposite1', Key.TVInputComposite1],
  ['TVInputComposite2', Key.TVInputComposite2],
  ['TVInputHDMI1', Key.TVInputHDMI1],
  ['TVInputHDMI2', Key.TVInputHDMI2],
  ['TVInputHDMI3', Key.TVInputHDMI3],
  ['TVInputHDMI4', Key.TVInputHDMI4],
  ['TVInputVGA1', Key.TVInputVGA1],
  ['TVMediaContext', Key.TVMediaContext],
  ['TVNetwork', Key.TVNetwork],
  ['TVNumberEntry', Key.TVNumberEntry],
  ['TVPower', Key.TVPower],
  ['TVRadioService', Key.TVRadioService],
  ['TVSatellite', Key.TVSatellite],
  ['TVSatelliteBS', Key.TVSatelliteBS],
  ['TVSatelliteCS', Key.TVSatelliteCS],
  ['TVSatelliteToggle', Key.TVSatelliteToggle],
  ['TVTerrestrialAnalog', Key.TVTerrestrialAnalog],
  ['TVTerrestrialDigital', Key.TVTerrestrialDigital],
  ['TVTimer', Key.TVTimer],

  // Media controller keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#media_controller_keys
  ['AVRInput', Key.AVRInput],
  ['AVRPower', Key.AVRPower],
  ['ColorF0Red', Key.ColorF0Red],
  ['ColorF1Green', Key.ColorF1Green],
  ['ColorF2Yellow', Key.ColorF2Yellow],
  ['ColorF3Blue', Key.ColorF3Blue],
  ['ColorF4Grey', Key.ColorF4Grey],
  ['ColorF5Brown', Key.ColorF5Brown],
  ['ClosedCaptionToggle', Key.ClosedCaptionToggle],
  ['Dimmer', Key.Dimmer],
  ['DisplaySwap', Key.DisplaySwap],
  ['DVR', Key.DVR],
  ['Exit', Key.Exit],
  ['FavoriteClear0', Key.FavoriteClear0],
  ['FavoriteClear1', Key.FavoriteClear1],
  ['FavoriteClear2', Key.FavoriteClear2],
  ['FavoriteClear3', Key.FavoriteClear3],
  ['FavoriteRecall0', Key.FavoriteRecall0],
  ['FavoriteRecall1', Key.FavoriteRecall1],
  ['FavoriteRecall2', Key.FavoriteRecall2],
  ['FavoriteRecall3', Key.FavoriteRecall3],
  ['FavoriteStore0', Key.FavoriteStore0],
  ['FavoriteStore1', Key.FavoriteStore1],
  ['FavoriteStore2', Key.FavoriteStore2],
  ['FavoriteStore3', Key.FavoriteStore3],
  ['Guide', Key.Guide],
  ['GuideNextDay', Key.GuideNextDay],
  ['GuidePreviousDay', Key.GuidePreviousDay],
  ['Info', Key.Info],
  ['InstantReplay', Key.InstantReplay],
  ['Link', Key.Link],
  ['ListProgram', Key.ListProgram],
  ['LiveContent', Key.LiveContent],
  ['Lock', Key.Lock],
  ['MediaApps', Key.MediaApps],
  ['MediaAudioTrack', Key.MediaAudioTrack],
  ['MediaLast', Key.MediaLast],
  ['MediaSkipBackward', Key.MediaSkipBackward],
  ['MediaSkipForward', Key.MediaSkipForward],
  ['MediaStepBackward', Key.MediaStepBackward],
  ['MediaStepForward', Key.MediaStepForward],
  ['MediaTopMenu', Key.MediaTopMenu],
  ['NavigateIn', Key.NavigateIn],
  ['NavigateNext', Key.NavigateNext],
  ['NavigateOut', Key.NavigateOut],
  ['NavigatePrevious', Key.NavigatePrevious],
  ['NextFavoriteChannel', Key.NextFavoriteChannel],
  ['NextUserProfile', Key.NextUserProfile],
  ['OnDemand', Key.OnDemand],
  ['Pairing', Key.Pairing],
  ['PinPDown', Key.PinPDown],
  ['PinPMove', Key.PinPMove],
  ['PinPToggle', Key.PinPToggle],
  ['PinPUp', Key.PinPUp],
  ['PlaySpeedDown', Key.PlaySpeedDown],
  ['PlaySpeedReset', Key.PlaySpeedReset],
  ['PlaySpeedUp', Key.PlaySpeedUp],
  ['RandomToggle', Key.RandomToggle],
  ['RcLowBattery', Key.RcLowBattery],
  ['RecordSpeedNext', Key.RecordSpeedNext],
  ['RfBypass', Key.RfBypass],
  ['ScanChannelsToggle', Key.ScanChannelsToggle],
  ['ScreenModeNext', Key.ScreenModeNext],
  ['Settings', Key.Settings],
  ['SplitScreenToggle', Key.SplitScreenToggle],
  ['STBInput', Key.STBInput],
  ['STBPower', Key.STBPower],
  ['Subtitle', Key.Subtitle],
  ['Teletext', Key.Teletext],
  ['VideoModeNext', Key.VideoModeNext],
  ['Wink', Key.Wink],
  ['ZoomToggle', Key.ZoomToggle],

  // Speech recognition keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#speech_recognition_keys
  ['SpeechCorrectionList', Key.SpeechCorrectionList],
  ['SpeechInputToggle', Key.SpeechInputToggle],

  // Document keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#document_keys
  ['Close', Key.Close],
  ['New', Key.New],
  ['Open', Key.Open],
  ['Print', Key.Print],
  ['Save', Key.Save],
  ['SpellCheck', Key.SpellCheck],
  ['MailForward', Key.MailForward],
  ['MailReply', Key.MailReply],
  ['MailSend', Key.MailSend],

  // Application selector keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#application_selector_keys
  ['LaunchCalculator', Key.LaunchCalculator],
  ['LaunchCalendar', Key.LaunchCalendar],
  ['LaunchContacts', Key.LaunchContacts],
  ['LaunchMail', Key.LaunchMail],
  ['LaunchMediaPlayer', Key.LaunchMediaPlayer],
  ['LaunchMusicPlayer', Key.LaunchMusicPlayer],
  ['LaunchMyComputer', Key.LaunchMyComputer],
  ['LaunchPhone', Key.LaunchPhone],
  ['LaunchScreenSaver', Key.LaunchScreenSaver],
  ['LaunchSpreadsheet', Key.LaunchSpreadsheet],
  ['LaunchWebBrowser', Key.LaunchWebBrowser],
  ['LaunchWebCam', Key.LaunchWebCam],
  ['LaunchWordProcessor', Key.LaunchWordProcessor],
  ['LaunchApplication1', Key.LaunchApplication1],
  ['LaunchApplication2', Key.LaunchApplication2],
  ['LaunchApplication3', Key.LaunchApplication3],
  ['LaunchApplication4', Key.LaunchApplication4],
  ['LaunchApplication5', Key.LaunchApplication5],
  ['LaunchApplication6', Key.LaunchApplication6],
  ['LaunchApplication7', Key.LaunchApplication7],
  ['LaunchApplication8', Key.LaunchApplication8],
  ['LaunchApplication9', Key.LaunchApplication9],
  ['LaunchApplication10', Key.LaunchApplication10],
  ['LaunchApplication11', Key.LaunchApplication11],
  ['LaunchApplication12', Key.LaunchApplication12],
  ['LaunchApplication13', Key.LaunchApplication13],
  ['LaunchApplication14', Key.LaunchApplication14],
  ['LaunchApplication15', Key.LaunchApplication15],
  ['LaunchApplication16', Key.LaunchApplication16],

  // Browser control keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#browser_control_keys
  ['BrowserBack', Key.BrowserBack],
  ['BrowserFavorites', Key.BrowserFavorites],
  ['BrowserForward', Key.BrowserForward],
  ['BrowserHome', Key.BrowserHome],
  ['BrowserRefresh', Key.BrowserRefresh],
  ['BrowserSearch', Key.BrowserSearch],
  ['BrowserStop', Key.BrowserStop],

  // Numeric keypad keys
  // https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_values#numeric_keypad_keys
  ['Decimal', Key.Decimal],
  ['Key11', Key.Key11],
  ['Key12', Key.Key12],
  ['Multiply', Key.Multiply],
  ['Add', Key.Add],
  ['NumpadClear', Key.NumpadClear],
  ['Divide', Key.Divide],
  ['Subtract', Key.Subtract],
  ['Separator', Key.Separator],
  ['Key0', Key.Key0],
  ['Key1', Key.Key1],
  ['Key2', Key.Key2],
  ['Key3', Key.Key3],
  ['Key4', Key.Key4],
  ['Key5', Key.Key5],
  ['Key6', Key.Key6],
  ['Key7', Key.Key7],
  ['Key8', Key.Key8],
  ['Key9', Key.Key9],
]);
